### ISSUE TITLE
interface order

### ISSUE THREAD

**Issue by dividinglimits** [shomali11/slacker#1]
Its more idiomatic in Go to have the "outout/response" as the first argument.

```
func (w slacker.Response, r slacker.Request, ...
```

I think this is likely worth the breaking change since you have yet to make public release according to the github UI. cheers.

**Comment by dividinglimits** [comment]
further, i am interested in understanding the decision behind not just accepting the default handler https://golang.org/pkg/net/http/#Handler interface

**Comment by shomali11** [comment]
Thank you @dividinglimits! 
That is a good point, I actually did not know about the output/response being the first argument is the idiomatic Go way. Thanks for teaching me something new.

**Comment by shomali11** [comment]
As to why I did not use the http Handler interface, is because I did not feel it fits here. Whoever is going to use this framework, will not be expecting to deal with HTTP codes, Method, Headers, and such.

Plus I wanted to simplify the methods of the Request and the Response to give the user what they need and not overwhelm them with more.

However, I did go back and forth on whether I wanted to have the handler with two separate structs Request and Response, or just one struct Context.

As in `func(w slacker.Response, r slacker.Request)` vs `func(c slacker.Context)`

I ended up going with the Request/Response option because I felt it was mode readable.

**Comment by shomali11** [comment]
I have thought about it and I like having the Request parameter first.
For now, I am going to keep it the way it is. I really appreciate the suggestion. Please keep the feedback coming and let me know how I can improve the framework and what features I could potentially add 👍
