### ISSUE TITLE
How to retrieve raw payload / get the team_id?

### ISSUE THREAD

**Issue by geekyme** [shomali11/slacker#101]
`Data` on `BotContext.Event()` points to https://pkg.go.dev/github.com/slack-go/slack@v0.10.2/slackevents#MessageEvent and does not have the `team_id`

**Comment by arusso** [comment]
The code you're pointing to isn't slacker but in fact the underlying slack library we build on top of. If my comments below don't help, you should consider opening an issue with that project.

There's a similar [issue](https://github.com/slack-go/slack/issues/961) to what you're asking for though related to attachments. Looking at their example though, it doesn't look like the inner-event has the `team_id`. 

Depending on what you're trying to do exactly, it seems like you lookup the user details from the message event. Otherwise, you might check out the `UserTeam` / `SourceTeam` attributes. I haven't used them but I would expect team data to only be relevant when shared workspaces are at play, so this seems like it could be what you're after:

```
...
	// When Message comes from a channel that is shared between workspaces
	UserTeam   [string](https://pkg.go.dev/builtin#string) `json:"user_team,omitempty"`
	SourceTeam [string](https://pkg.go.dev/builtin#string) `json:"source_team,omitempty"`
...
```

But again, we're looking at the internals of the slack library and not slacker at this point.
