### ISSUE TITLE
Adding flags

### ISSUE THREAD

**Issue by piclemx** [shomali11/slacker#22]
Hey, i think this could be a cool improvement for slacker if we got something like
`https://github.com/spf13/cobra` 

with flags

Interesting you think?

**Comment by piclemx** [comment]
@shomali11 what do you think about this?

**Comment by shomali11** [comment]
I am not against it. Did you have some flags in mind other than the token and debug flag?

Feel free to put together a PR with integration with cobra!

**Comment by piclemx** [comment]
@shomali11 I was thinking this for the command from the bot. I don't think that will be done in slacker... not completely.. part will in commander i supposed.

Still interest? What will be the starting point.. I happy to contribute if you want to help me.

**Comment by shomali11** [comment]
Oh ... But wouldn't this change the style of how one interacts with the bot?

For example, instead of:

`@bot repeat hello 3`

it would be:

`@bot repeat --word hello --number 3`

I am open to it as long as the user has the option to pick between the `commander` style, the `cobra` style and perhaps define their own `custom` style.

I think that would make for a fantastic feature. If you could put together a PR, that would be great. I would be more than happy to help.

**Comment by piclemx** [comment]
In cobra, you can do something like 

```
@bot get words --filter foo
```

`get` is a command. `words` is a subcommand of `get`.

Do you have any idea where to start with this?

**Comment by shomali11** [comment]
I will close this for now until a PR is created with your idea
