### ISSUE TITLE
Capture at beginning of line captures ID as well as capture item

### ISSUE THREAD

**Issue by noqcks** [shomali11/slacker#28]
The capture 

```
bot.Command("<bot> <cluster>", "TODO", func(request slacker.Request, response slacker.ResponseWriter) {}
```
will return `<bot>` as 

```<@UABU3NX6D> foo```

But the capture
```
bot.Command("features <bot> <cluster>", "TODO", func(request slacker.Request, response slacker.ResponseWriter) {}
```
will return `<bot>` as 
```foo```

**Comment by shomali11** [comment]
My apologies for the late reply. I am currently traveling.

I am not quite sure I understand the problem. Could you elaborate with examples of the messages you are sending?

I am not understanding the usage of the `<bot>` parameter in the `Command` definition.

If it was up to me, I would define the command as follows:

```
bot.Command("cluster <cluster> info", "Cluster Information", func(request slacker.Request, response slacker.ResponseWriter) {}
```

So that it would respond to a message such as:

`@bot cluster abc info`

And the parameter `<cluster>` would be set to `abc`

Similarly, I would define the other command as:

```
bot.Command("cluster <cluster> features", "Cluster Features", func(request slacker.Request, response slacker.ResponseWriter) {}
```

So that it would respond to a message such as:

`@bot cluster abc features`

And the parameter `<cluster>` would be set to `abc`
