### ISSUE TITLE
Feature Request: ParseFunc to override parser

### ISSUE THREAD

**Issue by ayjayt** [shomali11/slacker#36]
Are you open to these feature improvements:

* CommandDefinition taking a `ParseFunc(string) interface{}` and uses this instead of default parser

 * CommandDefinition can override help string

I will implement this in my fork today but I was wondering if you had any feedback/were interested.

**Comment by shomali11** [comment]
That sounds like a good idea.

Regarding overriding the Help details, it should already be supported. Look at this example:
https://github.com/shomali11/slacker/blob/master/examples/example13.go#L37

As for the `ParseFunc(string) interface()`, could you elaborate on what exactly it will do? 
Do you intend for it to be used instead of the internal Regex Matching functionality? If so, this sounds like something that should be defined as a parameter to `NewClient` function or as a parameter passed to a method in the `bot` structure. Correct?

**Comment by ayjayt** [comment]
I'll look into soon so I can answer your question, but I was thinking:
`@bot command parameter parameter parameter parameter`
Then, parse only the parameters: "parameter1 parameter2 parameter3" for that command, and return some object defined by the user to be consumed by their command function.

I did this in my project, so that I could capture white-space inside parameters using quotations as delimiters:

*Inside command function:*
````
allParams := r.StringParam("all", "")
repo, title, body, err := parseParams(allParams)
````
*Registering command:*
````
// Register command
botLink.sBot.Command("new <all>", newIssue)
`````
