### ISSUE TITLE
Can't use attachments in Reply due to vendor'd code

### ISSUE THREAD

**Issue by minichate** [shomali11/slacker#42]
```
cannot use attachments (type []"github.com/nlopes/slack".Attachment) as type []"github.com/shomali11/slacker/vendor/github.com/nlopes/slack".Attachment in assignment
```

**Comment by shomali11** [comment]
I believe the problem is that we are exposing the `nlopes/slack` dependency in here:
https://github.com/shomali11/slacker/blob/master/defaults.go#L35

Probably what should be done is create a copy of the `Attachment` structure from `nlopes/slack`:
https://github.com/nlopes/slack/blob/master/attachments.go#L64

And then convert from the `slacker` `Attachment` structure to the `nlopes/slack` `Attachment` structure here:
https://github.com/shomali11/slacker/blob/master/defaults.go#L37

This way the end user does not have this conflict between the vendored dependency in `slacker` and the user's.

If you would like to put together a PR for this, I would very much appreciate it.

**Comment by shomali11** [comment]
Did you try using `dep ensure -add`?
