### ISSUE TITLE
When enabled threaded reply, two duplicate messages are delivered

### ISSUE THREAD

**Issue by goutamtadi1** [shomali11/slacker#82]
Code:
```
  definition := &slacker.CommandDefinition{
    Handler: func(botCtx slacker.BotContext, request slacker.Request, response slacker.ResponseWriter) {
      fmt.Println(botCtx.Event().BotID)
      image := request.Param("image")
      response.Reply(fmt.Sprintf("%s promoted here", image), slacker.WithThreadReply(true))
    },
  }

  bot.Command("promote <image>", definition)
```
Slack delivery:

![image](https://user-images.githubusercontent.com/8926556/130553598-343651de-4bba-4665-8a16-1f3bb2100c0d.png)

When removed the Thread delivery, I get only one response

**Comment by shomali11** [comment]
I am currently out of the country on vacation but maybe @arusso might be able to help in the meantime? He is awesome.

**Comment by arusso** [comment]
I’ll try and look at this tomorrow. What version (commit hash) of slacker are you running?

**Comment by goutamtadi1** [comment]
@arusso I'm using latest master I guess
```
github.com/shomali11/slacker v0.0.0-20210820202715-e3dbcff4056e
```

**Comment by arusso** [comment]
I can't reproduce this using [your example](https://gist.github.com/arusso/d07ff40de0868ca6ca89e52e6ea25dbb).

I wonder if there's something different about your setup that I'm not considering. What version of the slack-go library are you using? SocketMode should ensure even if you have multiple bots running, it will only send it to one instance (unless somehow one instance is receiving but not acknowledging it?) so that doesn't seem likely.

Here's the result I get:

<img width="366" alt="Screen Shot 2021-08-24 at 10 20 08 PM" src="https://user-images.githubusercontent.com/561997/130731275-ef9c4782-6de0-4da7-b0c0-ad78e81c6551.png">

**Comment by arusso** [comment]
Ah! I was able to reproduce it after reviewing your initial report. It only happens when you @ mention the bot.


If you want the bot to only respond when you mention it, you should remove the `message:channel` and `message:im` event subscriptions. If you want it to respond even if it's not mentioned, remove the `app_mention` subscription.

I don't think there's going to be a way to solve this in Slacker for you -- the bot is going to get two independent events due to the event subscriptions you've enabled.
